name: Parsers
on: [pull_request, push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.10.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r dev-requirements.txt
      - name: Test SPM parser
        run: |
          curl -LJO https://raw.githubusercontent.com/incf-nidash/nidmresults-examples/master/spm_explicit_mask/batch.m
          python -m bids_prov.spm.spm_parser --input_file batch.m --output_file explicit_mask.json
      - name: Test FSL Parser
        run: |
          python -m bids_prov.fsl.fsl_parser --input_file examples/fsl_default/logs.md --output_file  tests.json
      - name: Test AFNI Parser
        run: |
          wget https://raw.githubusercontent.com/incf-nidash/nidmresults-examples/master/afni_default/subject_results/group.DS0011/subj.sub_001/proc.sub_001
          python -m bids_prov.afni.afni_parser --input_file proc.sub_001 --output_file  tests.json