name: SPM_on_nidm_examples              
on: 
  push:
    branches: [correc_parser]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.10.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          sudo apt-get install graphviz
      - name: Test SPM parser on SPM nidm examples
        run: |
          python Launch_multiple_spm.py