name: Unit tests for SPM,FSL and AFNI exporter
on: [pull_request, push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.10.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r dev-requirements.txt
      - name: Unit tests
        run: pytest -s bids_prov 